<a href="https://colab.research.google.com/github/ishitaa27/PageRankingAlgorithm/blob/main/IR_2a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import scipy

In [ ]:
#To calculate eigen vector
def left_eigen(n,c,e_list):
  mat = np.zeros((n,n))
  MAT = np.zeros((n,n))
  for i in range(c):
    x = e_list[i][0]
    y = e_list[i][1]
    mat[(x-1)][(y-1)] = 1
    MAT[(x-1)][(y-1)] = 1
  for i in range(n):
    mat[i]= mat[i]/sum(mat[i])
  v, V = np.linalg.eig(mat.T)
  left_ev = V[:,0].T
  left_ev.sort()
  return left_ev, mat, MAT
  


In [ ]:
def left_eigen_vector(mat):
  v, V = np.linalg.eig(mat.T)
  left_ev = V[:,0].T
  left_ev.sort()
  return left_ev


In [ ]:
#To calculate the teleportation matrix
def cal_teleportation(MAT):
  alpha = 0.1
  for i in range(nodes):
    for j in range(nodes):
      if (MAT[i][j]==0):
        MAT[i][j] = alpha/List_N_M[i][0]
      else:
        MAT[i][j] = MAT[i][j]*(1-alpha)/List_N_M[i][1]
  return MAT

In [ ]:
#Taking the input
nodes = int(input('Number of nodes:'))
connections = int(input('Number of connections:'))
edges = input('Enter the edges:')
edges = edges.split(' ')
edges_list = []
for i in range(connections):
  edges_list.append(tuple(int(x) for x in edges[i].split(',')))

Number of nodes:4
Number of connections:6
Enter the edges:1,2 2,1 2,3 3,2 3,4 4,3


In [ ]:
EigenVector, Mat, MAT = left_eigen(nodes,connections,edges_list)
List_N_M =[]
for i in range(nodes):
  N=0 #any page teleportation total
  M=0 #can go to only these pages
  for j in range(nodes):
    if (MAT[i][j] == 0):
      N = N+1
    else:
      M = M+1
  List_N_M.append((N,M))
#List_N_M  
#MAT
  

In [ ]:
print(List_N_M)

[(3, 1), (2, 2), (2, 2), (3, 1)]


In [ ]:
Teleportation_Matrix = cal_teleportation(MAT)
print(Teleportation_Matrix)

[[0.03333333 0.9        0.03333333 0.03333333]
 [0.45       0.05       0.45       0.05      ]
 [0.05       0.45       0.05       0.45      ]
 [0.03333333 0.03333333 0.9        0.03333333]]


In [ ]:
print(left_eigen_vector(Teleportation_Matrix))

[-0.62330046 -0.62330046 -0.33391096 -0.33391096]


In [26]:
#Power Iteration Method with Random Teleportation
r_0 = np.empty(nodes)
r_0.fill((1/nodes))
print(r_0)
count = 0
epochs = 50000
for i in range(epochs):
  convergence = r_0
  r_0 = np.dot(r_0, Teleportation_Matrix)
  count += 1
  converged = False
  for i in range(len(r_0)):
    if r_0[i] == convergence[i]:
      converged = True
  if converged:
    break
print(r_0)
print("The number of iterations it took for convergence is ", count)
#print(np.sum(r_0))

[0.25 0.25 0.25 0.25]
[0.1744186 0.3255814 0.3255814 0.1744186]
The number of iterations it took for convergence is  43


In [27]:
#Power Iteration Method without Random Teleportation
EigenVector, Mat, MAT = left_eigen(nodes,connections,edges_list)
x_0 = np.empty(nodes)
x_0.fill((1/nodes))
print(x_0)
count = 0
epochs = 50000
for i in range(epochs):
  convergence = x_0
  x_0 = np.dot(x_0, Mat)
  count += 1
  converged = False
  for i in range(len(x_0)):
    if x_0[i] == convergence[i]:
      converged = True
  if converged:
    break
print(x_0)
print("The number of iterations it took for convergence is ", count)

[0.25 0.25 0.25 0.25]
[0.16666667 0.33333333 0.33333333 0.16666667]
The number of iterations it took for convergence is  54
